workflows:
  expo-apk:
    name: Expo APK Build
    max_build_duration: 60
    environment:
      node: latest
      vars:
        EAS_NO_VCS: "1"
        EXPO_TOKEN: $EXPO_TOKEN
    scripts:
      - name: Install dependencies
        script: |
          npm install -g eas-cli
          npm install
      - name: Build APK
        script: |
          eas build -p android --profile preview --non-interactive
    artifacts:
      - build/**/*.apk
    cache:
      cache_paths:
        - $HOME/.npm
        - $HOME/.cache/eas



