workflows:
  expo-apk:
    name: Expo APK Build
    max_build_duration: 60
    environment:
      vars:
        EAS_NO_VCS: "1"
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install -g eas-cli
          npm install
      - name: Build APK
        script: |
          eas build -p android --profile preview --non-interactive
    artifacts:
      - build/**/*.apk


